Add a session post addon
bloxlink/Bloxlink pull request #15
Opened 2020-12-21 20:52 UTC by yogurtsyum

Hello there!

I have created a session poster addon for Bloxlink, so when addons are released this can be used as one of them.
Here's how it looks:
![image](https://i.gyazo.com/ad0fbd0f37372685871c8c1faed28c31.gif)

Please let me know if you would like me to make any changes to this to support any future updates you make to addons by either messaging me on Discord at Lengo#0001 or mentioning/pinging me here.

2020-12-22 00:53 UTC, yogurtsyum commented
I'm going to add a command to update the embed and mark it as finished or in process soon.

2020-12-23 21:04 UTC, yogurtsyum commented
I just finished making some updates so the addon so that sessions can be marked as ended or in progress. I am going to test it today and add it to this pull request tomorrow.

2020-12-24 05:45 UTC, xomien requested changes

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +        self.dm_allowed = False
This is redundant.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +        self.free_to_use = True
This is redundant.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +        self.category = "Miscellaneous"
This is redundant.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "embed_color": INVISIBLE_COLOR
Please use the default color for the prompts. So, this dictionary pair can be removed.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "name": "dateAndTime",
Please follow the snake_case convention for variables.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +    @Bloxlink.flags
@Bloxlink.flags is a resource-intensive process that extracts flags and provides them to the command. If you're not going to use flags, then don't call this.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +        embed = Embed(title=f"{title}")
f-strings aren't needed if you're not doing in-text replacement.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +        await channel.send(embed=embed)
Please catch Forbidden and NotFound. These can be imported from discord.errors.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "exceptions": ["skip"]
Exceptions aren't needed if you're using string arguments.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +class SessionAddon:
I told you in the Discord server that add-ons weren't implemented and the final add-on structure isn't final. Please do not implement the add-on framework this early on.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +        prefix = CommandArgs.prefix
This variable doesn't appear to be used.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "embed_color": INVISIBLE_COLOR
See my earlier comment.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "embed_color": INVISIBLE_COLOR,
See my earlier comment.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "embed_color": INVISIBLE_COLOR
See my earlier comment.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "prompt": "Who is hosting this session?",
Might be better to use the "user" argument type instead. This will give you a Discord user. You can default to the original author if they try to skip it, though.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "prompt": "Who is co-hosting this session?",
See my earlier comment about the "user" argument type.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "embed_color": INVISIBLE_COLOR
See my earlier comment.

2020-12-24 05:45 UTC, xomien commented on src/addons/session.py
> +                "embed_color": INVISIBLE_COLOR,
See my earlier comment.

2020-12-24 05:54 UTC, xomien commented
> I'm going to add a command to update the embed and mark it as finished or in process over the next few days.

I recommend this be in a sub-command format. One example is from the data command: https://github.com/bloxlink/Bloxlink/blob/master/src/commands/data.py

Also, for now, you can save it all in memory, but later on, I will edit this to save it in the database instead.

2020-12-30 19:18 UTC, yogurtsyum commented
Just a quick update on this, I am almost finished with the updates, I just have a few small bugs to fix and will try my best to get it added to this pull request by tomorrow.

2020-12-31 03:29 UTC, xomien commented
Sounds good, thanks.

2021-01-02 22:27 UTC, yogurtsyum commented on src/addons/session.py
> +        self.dm_allowed = False
Which part of this?

2021-01-03 07:20 UTC, xomien commented on src/addons/session.py
> +        self.dm_allowed = False
The last line. All reviews are for the last lines in the code snippets. In this case, dm_allowed=False isn't needed since it already defaults to False.

2021-01-03 18:23 UTC, yogurtsyum commented
I just added my changes to the session addon based on your review to the pull request. Now, there are two subcommands to !session, which are create and update. If you choose create, you go through a similar creation prompt as shown in the gif above. If you choose update, you are asked to enter the message id of the session (which is now in the footer of the session embed so you don't need developer mode activated), and then pick whether to mark the session as in progress or ended.

The embed title and color are updated according to the session's status. I'll see if I can post a gif here soon with a demonstration of the new features.

2021-01-12 04:54 UTC, xomien commented
Sorry for the late response. I'm currently putting this on pause; I'll resume this PR when we implement the feed system internally. This is estimated to be done after the server dashboard. The system will let us sufficiently do certain actions such as group shout posting, and the session posting as well.

2021-02-21 22:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bloxlink/Bloxlink?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bloxlink/Bloxlink?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bloxlink/Bloxlink?pullRequest=15) it.</sub>

2022-05-07 05:53 UTC, julien777z commented
Hi, unfortunately, this isn't compatible with our existing infrastructure.

2022-05-07 05:53 UTC, closed without merging